# Generated by Django 4.2.21 on 2025-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reimbursement",
            name="type",
            field=models.CharField(
                choices=[
                    ("reimbursement", "Reimbursement"),
                    ("bonus_encashment", "Bonus Point Encashment"),
                    ("medical_encashment", "Medical Encashment"),
                    ("leave_encashment", "Leave Encashment"),
                ],
                default="reimbursement",
                max_length=20,
            ),
        ),
    ]
