# Generated by Django 4.2.21 on 2025-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_reimbursementconditionapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="claim_for",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Self"),
                    ("mother", "Mother"),
                    ("father", "Father"),
                    ("son", "Son"),
                    ("daughter", "Daughter"),
                    ("wife", "Wife"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="dependent_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="medical_expenses",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="total_claimed_amount",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
