# Generated by Django 4.2.21 on 2025-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0004_reimbursement_claim_for_reimbursement_dependent_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="reject_reason",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Rejection Reason"
            ),
        ),
        migrations.AddField(
            model_name="reimbursement",
            name="rejected_by_department",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Rejected By Department",
            ),
        ),
        migrations.AddField(
            model_name="reimbursementconditionapproval",
            name="reject_reason",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Rejection Reason"
            ),
        ),
    ]
