# Generated by Django 4.2.21 on 2025-09-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_reimbursement_reject_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reimbursement",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("closed", "Closed"),
                ],
                default="requested",
                editable=False,
                max_length=10,
            ),
        ),
    ]
