# Generated by Django 4.2.21 on 2025-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_alter_reimbursement_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="finance_comment",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
