# Generated by Django 4.2.21 on 2025-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timesheet",
            name="task_id",
        ),
        migrations.AddField(
            model_name="timesheet",
            name="task_name",
            field=models.CharField(default="", max_length=255, verbose_name="Task"),
        ),
    ]
