# Generated by Django 4.2.21 on 2025-10-07 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0001_initial"),
        ("project", "0002_remove_timesheet_task_id_timesheet_task_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("task_name", models.CharField(max_length=255, verbose_name="Task")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Date"
                    ),
                ),
                (
                    "total_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Seconds"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_time_logs",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_time_logs",
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_time_logs",
                        to="project.timesheet",
                        verbose_name="Timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Time Log",
                "verbose_name_plural": "Task Time Logs",
                "ordering": ("-date", "-id"),
                "unique_together": {("employee", "project", "task_name", "date")},
            },
        ),
    ]
