# Generated by Django 4.2.21 on 2025-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="multipleapprovalcondition",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("leave", "Leave Request"),
                    ("medical_reimbursement", "Medical Reimbursement"),
                ],
                default="leave",
                max_length=50,
                verbose_name="Condition",
            ),
        ),
        migrations.AlterField(
            model_name="multipleapprovalcondition",
            name="condition_field",
            field=models.CharField(
                blank=True,
                choices=[("", "---------"), ("requested_days", "Leave Requested Days")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="multipleapprovalcondition",
            name="department",
        ),
        migrations.AddField(
            model_name="multipleapprovalcondition",
            name="department",
            field=models.ManyToManyField(to="base.department"),
        ),
    ]
